### ISSUE TITLE
Informative materials.. 

### ISSUE THREAD

**Issue by scalet98** [jtwhite79/decision_support_analysis_notebooks#1]
Hello Jeremy ! 
This looks very Informative materials.. 
I send you an email with some question on this issue. 
But it continuously gave me an error message that your account(jwhite@usgs.gov) is missing. 
Anyhow 2 simple questions. 

Firstly, do you have online lecture in terms of these materials? 
Secondly, I am studying watershed modeling under deep uncertainty but I want to consider ground water in my modeling. 
Do you have any reference research materials or paper suggestion related to the integration of those two model considering uncertainty issue? 

Please let me know. 
Thanks 

Jiheon Scarlett Lee 
career03@hotmail.com
scalet98@chungbuk.ac.kr

**Comment by jtwhite79** [comment]
I'm in the process of covering these materials in online sessions and they are being recorded.  I'll look into posting those videos.

**Comment by scalet98** [comment]
Good to know about your plan. 
hope to listen good news soon. 
Thank you ! 

Jiheon Scarlett Lee :)

**Comment by scalet98** [comment]
Good to know about your plan. 
hope to listen good news soon. 
Thank you ! 

Jiheon Scarlett Lee :)
